name: NX_CI

on:
  workflow_dispatch:
  push:
    branches:
      - forward
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: spliting string
      uses: winterjung/split@v2.1.0
      id: repo
      with:
        msg: ${{ github.repository }}
        separator: '/'
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: forward
        submodules: recursive
    - name: Build
      run: |
        git config --global --add safe.directory `pwd`
        git submodule update --remote 
        wget https://raw.githubusercontent.com/zerofo/nx-ovlloader/refs/heads/forward/hbl.json
        mv hbl.json config.json
        make nx -j $(nproc);
        apt install imagemagick tree -y
        #tree .
        mkdir -p hblmenu_NSP/exefs
        mkdir -p hblmenu_NSP/control
        cp build/exefs/* hblmenu_NSP/exefs/
        convert icon.jpg -resize 256x256 icon_AmericanEnglish.jpg
        cp icon_AmericanEnglish.jpg hblmenu_NSP/control/
        cp -r romfs hblmenu_NSP/
        #npdmtool config.json hblmenu_NSP/exefs/main.npdm
        #nacptool --create "hblmenu" "zerofo" "v0.1" hblmenu_NSP/control/control.nacp --titleid 010078787878100D
        cp nx-hbmenu.nacp hblmenu_NSP/control/control.nacp
        ################### packing NSP #####################
        # wget https://github.com/DeaconBlood/PROD.KEYS/releases/latest/download/prod.keys
        wget https://github.com/DeaconBlood/PROD.KEYS/releases/download/KEYS/prod.keys
        wget https://github.com/zerofo/hacBrewPack/releases/latest/download/hacbrewpack
        sudo -E chmod +x ./hacbrewpack
        ./hacbrewpack -k prod.keys --exefsdir hblmenu_NSP/exefs/ --controldir hblmenu_NSP/control --titleid 010078787878100D \
          --romfsdir hblmenu_NSP/romfs --nologo --plaintext --nosignncasig2 --nopatchnacplog --nspdir output
         mv ./output/010078787878100d.nsp ./hblmenu-NSP_010078787878100d.nsp
    - name: Upload file
      uses: actions/upload-artifact@v4
      with:
        # name: ${{ steps.repo.outputs._1 }} 
        path: ./*.nsp
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.release_token }}
        file: ./*.nsp
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
